### ISSUE TITLE
Module is not Working

### ISSUE THREAD

**Issue by iurimedeiros** [magmodules/magento2-messagebird#2]
Hello friends,

I notice that apparently the module is no longer functional, when trying to install it in Magento 2.4.4-p1, PHP 8.1 through composer, it does not continue.

I performed the installation manually, but when I clicked to check the credentials, it just keeps loading and does not validate.

I enabled Debug Mode, but it is not recording any log, I could only identify the following errors in Magento system.log:

Next ReflectionException: Impossible to process constructor argument Parameter #0 [ <required> MessageBird\Objects\Message $message ] of Magmodules\MessageBird\Service\Api\Adapter class in /chroot/home/a151c07b/ab1e1aef90.nxcli.net/html/vendor/magento/framework/Code/Reader/ClassReader.php:57
Stack trace:
#0 /chroot/home/a151c07b/ab1e1aef90.nxcli.net/html/vendor/magento/framework/ObjectManager/Definition/Runtime.php(54): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magmodules\\Mess...')
#1 /chroot/home/a151c07b/ab1e1aef90.nxcli.net/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(48): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magmodules\\Mess...')
#2 /chroot/home/a151c07b/ab1e1aef90.nxcli.net/html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magmodules\\Mess...')
#3 /chroot/home/a151c07b/ab1e1aef90.nxcli.net/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get('Magmodules\\Mess...')
#4 /chroot/home/a151c07b/ab1e1aef90.nxcli.net/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magmodules\\Mess...', NULL, 'adapter', 'Magmodules\\Mess...')
#5 /chroot/home/a151c07b/ab1e1aef90.nxcli.net/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magmodules\\Mess...', Array, Array)
#6 /chroot/home/a151c07b/ab1e1aef90.nxcli.net/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magmodules\\Mess...', Array, Array)
#7 /chroot/home/a151c07b/ab1e1aef90.nxcli.net/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magmodules\\Mess...', Array, Array)
#8 /chroot/home/a151c07b/ab1e1aef90.nxcli.net/html/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magmodules\\Mess...', Array)
#9 /chroot/home/a151c07b/ab1e1aef90.nxcli.net/html/vendor/magento/framework/App/ActionFactory.php(44): Magento\Framework\ObjectManager\ObjectManager->create('Magmodules\\Mess...')
#10 /chroot/home/a151c07b/ab1e1aef90.nxcli.net/html/vendor/magento/framework/App/Router/Base.php(306): Magento\Framework\App\ActionFactory->create('Magmodules\\Mess...')

**Comment by Marvin-Magmodules** [comment]
Hello @iurimedeiros, thank you for opening this issue. Looks like the required `messagebird/php-rest-api`module is missing. Did you install it using composer or did you do a module drop-in using ftp?

**Comment by Marvin-Magmodules** [comment]
Hi @iurimedeiros, great that this is resolved, thank you for the update.
